/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.placeholder.PlaceHolder;
import controllers.DepartmentController;
import controllers.EmployeeController;
import controllers.JobController;
import icontrollers.IDepartmentController;
import icontrollers.IEmployeeController;
import icontrollers.IJobController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Department;
import models.Employee;
import models.Job;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import tools.DBConnection;

/**
 *
 * @author HENSTECH
 */
public class EmployeeView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeView
     */
    DBConnection connection = new DBConnection();
    IEmployeeController iec = new EmployeeController(connection.getConnection());
    IJobController ijc = new JobController(connection.getConnection());
    IDepartmentController idc = new DepartmentController(connection.getConnection());

    DefaultTableModel model;

    public EmployeeView() {
        initComponents();
        placenya();
        model = (DefaultTableModel) tblEmployee.getModel();
        refresh();
        for (Job j : ijc.getAll()) {
            cbJobId.addItem(j.getId());
        }
        for (Employee e : iec.getAll()) {
            cbManagerId.addItem(e.getId());
        }

        for (Department d : idc.getAll()) {
            cbDepartmentId.addItem(d.getId());
        }

    }

    public void refresh() {
        model.setRowCount(0);
        Object[] row = new Object[12];
        List<Employee> employee = new ArrayList();
        employee = iec.getAll();

        for (int i = 0; i < employee.size(); i++) {
            row[0] = i + 1;
            row[1] = employee.get(i).getId();
            row[2] = employee.get(i).getFirstName();
            row[3] = employee.get(i).getLastName();
            row[4] = employee.get(i).getEmail();
            row[5] = employee.get(i).getPhoneNumber();
            row[6] = employee.get(i).getHireDate();
            row[7] = employee.get(i).getJobID();
            row[8] = employee.get(i).getSalary();
            row[9] = employee.get(i).getCommisionPCT();
            row[10] = employee.get(i).getManagerID();
            row[11] = employee.get(i).getDepartmentID();
            model.addRow(row);
        }

    }

    public void reset() {
        txtId.setEditable(true);
        txtId.setText("");
        txtFirst.setText("");
        txtLast.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtHire.setText("");
        cbJobId.setSelectedItem("");
        txtSalary.setText("");
        txtCommision.setText("");
        cbManagerId.setSelectedItem("");
        cbDepartmentId.setSelectedItem("");
        placenya();
    }

    public void placenya() {
        PlaceHolder holder1 = new PlaceHolder(txtId, "ID");
        PlaceHolder holder2 = new PlaceHolder(txtFirst, "Nama Awal");
        PlaceHolder holder3 = new PlaceHolder(txtLast, "Nama Akhir");
        PlaceHolder holder4 = new PlaceHolder(txtEmail, "contoh@mail.com");
        PlaceHolder holder5 = new PlaceHolder(txtPhone, "087908XXXX");
        PlaceHolder holder6 = new PlaceHolder(txtHire, "MM/DD/YYYY");
        PlaceHolder holder7 = new PlaceHolder(txtSalary, "Masukkan Gaji");
        PlaceHolder holder8 = new PlaceHolder(txtCommision, "Masukkan Commicion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtHire = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtCommision = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        txtSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbJobId = new javax.swing.JComboBox();
        cbManagerId = new javax.swing.JComboBox();
        cbDepartmentId = new javax.swing.JComboBox();
        btnReset = new javax.swing.JButton();
        jComboSelect = new javax.swing.JComboBox();
        btnReport = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Employee ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Phone Number");

        jLabel6.setText("Hire Date");

        jLabel7.setText("Job ID");

        jLabel8.setText("Salary ");

        jLabel9.setText("Commission PCT");

        jLabel10.setText("Manager ID");

        jLabel11.setText("Department ID");

        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "First Name", "Last Name", "Email", "Phone Number", "Hire Date", "Job ID", "Salary", "Commision PCT", "Manager ID", "Department ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployee);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("EMPLOYEES");

        cbJobId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbJobIdFocusGained(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jComboSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Select-", "Select", "Select only ID" }));
        jComboSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelectActionPerformed(evt);
            }
        });

        btnReport.setText("Print Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(292, 292, 292)
                                .addComponent(btnReport)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(239, 239, 239)
                                            .addComponent(btnSave)
                                            .addGap(55, 55, 55)
                                            .addComponent(btnDelete))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHire, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel11))
                                            .addGap(23, 23, 23)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtSalary)
                                                .addComponent(txtCommision)
                                                .addComponent(cbJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jComboSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)))
                                .addGap(117, 117, 117)
                                .addComponent(btnReset)
                                .addGap(43, 43, 43))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCommision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Data anda akan dihapus", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_NO_OPTION) {
            JOptionPane.showMessageDialog(null, iec.delete(txtId.getText()));
            refresh();
            reset();
        }


    }//GEN-LAST:event_btnDeleteActionPerformed


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JOptionPane.showMessageDialog(null, iec.save(txtId.getText(), txtFirst.getText(), txtLast.getText(),
                txtEmail.getText(), txtPhone.getText(), txtHire.getText(),
                cbJobId.getSelectedItem().toString(), txtSalary.getText(), txtCommision.getText(),
                cbManagerId.getSelectedItem().toString(), cbDepartmentId.getSelectedItem().toString()));
        refresh();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:

        txtId.setEditable(false);
        btnSave.setEnabled(true);
        int SelectRowIndex = tblEmployee.getSelectedRow();
        txtId.setText(model.getValueAt(SelectRowIndex, 1).toString());
        txtFirst.setText(model.getValueAt(SelectRowIndex, 2).toString());
        txtLast.setText(model.getValueAt(SelectRowIndex, 3).toString());
        txtEmail.setText(model.getValueAt(SelectRowIndex, 4).toString());
        txtPhone.setText(model.getValueAt(SelectRowIndex, 5).toString());
        txtHire.setText(model.getValueAt(SelectRowIndex, 6).toString());
        cbJobId.setSelectedItem(model.getValueAt(SelectRowIndex, 7).toString());
        txtSalary.setText(model.getValueAt(SelectRowIndex, 8).toString());
        txtCommision.setText(model.getValueAt(SelectRowIndex, 9).toString());
        cbManagerId.setSelectedItem(model.getValueAt(SelectRowIndex, 10).toString());
        cbDepartmentId.setSelectedItem(model.getValueAt(SelectRowIndex, 11).toString());

        txtId.setEditable(false);

    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIdMouseClicked

    private void cbJobIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbJobIdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJobIdFocusGained

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
        refresh();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jComboSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSelectActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        List<Employee> act2 = iec.search(txtSearch.getText().toLowerCase());
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        List<Employee> employee = new ArrayList<>();
        int count = 0;
        Object[] row = new Object[12];
        if (jComboSelect.getSelectedItem().equals("Select")) {
            employee = iec.search(txtSearch.getText());
            for (Employee e : iec.search(txtSearch.getText())) {

                row[0] = count + 1;
                row[1] = employee.get(count).getId();
                row[2] = employee.get(count).getFirstName();
                row[3] = employee.get(count).getLastName();
                row[4] = employee.get(count).getEmail();
                row[5] = employee.get(count).getPhoneNumber();
                row[6] = employee.get(count).getHireDate();
                row[7] = employee.get(count).getJobID();
                row[8] = employee.get(count).getSalary();
                row[9] = employee.get(count).getCommisionPCT();
                row[10] = employee.get(count).getManagerID();
                row[11] = employee.get(count).getDepartmentID();
                model.addRow(row);
                count = count + 1;
            }
        } else if (jComboSelect.getSelectedItem().equals("Select only ID")) {
            if (txtSearch.getText().replaceAll("[0-9]", "").equals("")) {
                employee = iec.getById(txtSearch.getText());
                for (Employee e : iec.getById(txtSearch.getText())) {

                    row[0] = count + 1;
                    row[1] = employee.get(count).getId();
                    row[2] = employee.get(count).getFirstName();
                    row[3] = employee.get(count).getLastName();
                    row[4] = employee.get(count).getEmail();
                    row[5] = employee.get(count).getPhoneNumber();
                    row[6] = employee.get(count).getHireDate();
                    row[7] = employee.get(count).getJobID();
                    row[8] = employee.get(count).getSalary();
                    row[9] = employee.get(count).getCommisionPCT();
                    row[10] = employee.get(count).getManagerID();
                    row[11] = employee.get(count).getDepartmentID();
                    model.addRow(row);
                    count = count + 1;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data harus angka!");
            }
        }


    }//GEN-LAST:event_jComboSelectActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

        String reportSource = null;
        String reportDest = null;
        try {
            reportSource = System.getProperty("user.dir") + "/src/reports/reportEmployees2.jrxml";
            reportDest = System.getProperty("user.dir") + "/src/reports/reportEmployees2.report";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, connection.getConnection());
            JasperExportManager.exportReportToPdfFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportActionPerformed

//    private void Report() {
//
//        try {
//            String reportSource = System.getProperty("user.dir") + "/src/reports/reportEmployees2.jrxml";
//
//            JasperDesign jd = JRXmlLoader.load("F:\\Net Beans\\Project\\Chit\\src\\Report\\report1.jrxml");
//            JasperReport report = JasperCompileManager.compileReport(jd);
//            JasperPrint jasperPrint = JasperFillManager.fillReport(report, null, dataSource);
//            JRViewer viewer = new JRViewer(jasperPrint);
//            Container c = getContentPane();
//            c.setLayout(new BorderLayout());
//            c.add(viewer);
//            //  JasperViewer.viewReport(jasperPrint);  //this is for Mainframe Display Seprately
//        } catch (JRException ex) {
//            System.out.println(ex);
//            Logger.getLogger(MemberReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbDepartmentId;
    private javax.swing.JComboBox cbJobId;
    private javax.swing.JComboBox cbManagerId;
    private javax.swing.JComboBox jComboSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtCommision;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtHire;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
